import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, MapPin, X, ZoomIn } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { type GalleryImage } from '../data/gallery';
import Dialog from '../components/Dialog';
export default function GalleryPage(){
  const [params]=useSearchParams();const [images,setImages]=useState<GalleryImage[]>([]);const [category,setCategory]=useState('All');const [selected,setSelected]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=()=>{setLoading(true);setError('');fetch('/api/gallery').then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>setImages(d.images)).catch(()=>setError('We couldn’t load the gallery. Please try again.')).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const filtered=images.filter(i=>(category==='All'||i.category===category)&&(!params.get('location')||i.location.toLowerCase().includes(params.get('location')!.toLowerCase())));
  const index=filtered.findIndex(i=>i.id===selected);const image=filtered[index];
  const move=(step:number)=>setSelected(filtered[(index+step+filtered.length)%filtered.length]?.id||null);
  useEffect(()=>{if(!selected)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setSelected(filtered[(index-1+filtered.length)%filtered.length]?.id||null);if(e.key==='ArrowRight')setSelected(filtered[(index+1)%filtered.length]?.id||null);};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[selected,index,filtered]);
  return <main><section className="page-heading"><div className="site-container"><p className="eyebrow">LIFE POWERED BY SOLAR</p><h1>Our work, in pictures.</h1><p>A closer look at STETECH installations, our team at work and solar solutions across Kenya.</p></div></section><section className="site-container section-space"><div className="mb-8 flex flex-wrap gap-2" aria-label="Gallery categories">{['All',...new Set(images.map(i=>i.category))].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)} className={`rounded-full border px-5 py-2.5 text-sm font-bold ${c===category?'border-emerald-800 bg-emerald-800 text-white':'border-slate-200 bg-white text-slate-600 hover:border-emerald-500'}`}>{c}</button>)}</div>{loading?<p role="status" className="py-16 text-center text-slate-500">Loading gallery…</p>:error?<div role="alert" className="py-16 text-center"><p>{error}</p><button onClick={load} className="text-link mt-4">Try again</button></div>:<><div className="gallery-grid">{filtered.map(item=><button className="gallery-card group animate-fade-in-up" key={item.id} onClick={()=>setSelected(item.id)} aria-label={`Enlarge ${item.title}`}><div className="relative"><img src={item.src} alt={item.title} loading="lazy" /><span className="absolute bottom-4 right-4 rounded-full bg-white/95 p-3 text-emerald-800 transition group-hover:scale-110"><ZoomIn size={19}/></span></div><div className="caption"><h3>{item.title}</h3><p className="flex items-center gap-1.5"><MapPin size={14}/>{item.location || item.category}</p></div></button>)}</div>{!filtered.length&&<p className="py-16 text-center text-slate-500">No photos in this collection yet.</p>}</>}</section>{image&&<Dialog label={image.title} onClose={()=>setSelected(null)} className="max-w-5xl"><button className="absolute right-3 top-3 z-10 rounded-full bg-white p-2 shadow" aria-label="Close photo" onClick={()=>setSelected(null)}><X/></button><div className="relative bg-slate-950"><img key={image.id} src={image.src} alt={image.title} className="max-h-[70dvh] w-full object-contain animate-modal-in"/>{filtered.length>1&&<><button onClick={()=>move(-1)} aria-label="Previous photo" className="absolute left-3 top-1/2 rounded-full bg-white p-2"><ChevronLeft/></button><button onClick={()=>move(1)} aria-label="Next photo" className="absolute right-3 top-1/2 rounded-full bg-white p-2"><ChevronRight/></button></>}</div><div className="flex items-start justify-between gap-4 p-5"><div><h2 className="font-bold">{image.title}</h2><p className="mt-1 text-sm text-slate-500">{image.location}</p></div><span className="text-sm text-slate-500">{index+1} / {filtered.length}</span></div></Dialog>}</main>;
}
