import { useEffect, useMemo, useState } from 'react';
import { Check, Minus, PackageSearch, Plus, Search, ShoppingBag, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import type { Product } from '../data/products';
import { getProductPrice, getProducts, syncProducts, formatKES } from '../data/productStore';
import { filterProducts, numericPrice } from '../data/productFilters';
import Dialog from '../components/Dialog';
type CartItem={product:Product;quantity:number};
const requestedCategories=['SOLAR PANEL','INVERTERS','SOLAR BATTERIES','SOLAR WATER PUMPS','SOLAR LIGHTING','SOLAR CHARGE CONTROLLERS','SOLAR CABLES','SOLAR ACCESSORIES'];
const representedProductCategories=['Solar Panels','Solar Inverters','Solar Batteries','Solar DC Pumps','Solar Floodlight and Streetlights','Solar Charge Controllers','Solar Accessories and Cables'];
export default function ProductsPage(){
  const [params,setParams]=useSearchParams();const [products,setProducts]=useState(getProducts);const [category,setCategory]=useState(params.get('category')||'All Products');const [query,setQuery]=useState('');const [sort,setSort]=useState('featured');const [availability,setAvailability]=useState('all');const [priceLimit,setPriceLimit]=useState('all');const [selected,setSelected]=useState<Product|null>(null);const [cart,setCart]=useState<CartItem[]>([]);const [checkout,setCheckout]=useState(false);const [customer,setCustomer]=useState({name:'',phone:'',location:'',notes:''});
  useEffect(()=>{const refresh=()=>setProducts(getProducts());window.addEventListener('stetech-products-updated',refresh);const focus=()=>void syncProducts();window.addEventListener('focus',focus);void syncProducts();return()=>{window.removeEventListener('stetech-products-updated',refresh);window.removeEventListener('focus',focus);};},[]);
  useEffect(()=>setCategory(params.get('category')||'All Products'),[params]);
  const categories=[...requestedCategories,...new Set(products.map(p=>p.category).filter(c=>!representedProductCategories.includes(c)))];
  const filtered=useMemo(()=>filterProducts(products,{category,query,sort,availability,priceLimit}),[products,category,query,sort,availability,priceLimit]);
  const setCat=(value:string)=>{setCategory(value);setParams(value==='All Products'?{}:{category:value},{replace:true});};
  const reset=()=>{setCat('All Products');setQuery('');setSort('featured');setAvailability('all');setPriceLimit('all');};
  const add=(p:Product)=>{setCart(items=>items.some(i=>i.product.id===p.id)?items.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...items,{product:p,quantity:1}]);setSelected(null);setCheckout(true);};
  const change=(id:number,delta:number)=>setCart(items=>items.map(i=>i.product.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0));
  const total=cart.reduce((n,i)=>n+(numericPrice(i.product)||0)*i.quantity,0);const count=cart.reduce((n,i)=>n+i.quantity,0);const unknown=cart.some(i=>numericPrice(i.product)===null);
  const submit=(e:React.FormEvent)=>{e.preventDefault();const message=`Hello STETECH, I would like to order:\n${cart.map(i=>`${i.product.name} × ${i.quantity}: ${numericPrice(i.product)===null?'Please quote':formatKES(numericPrice(i.product)!*i.quantity)}`).join('\n')}\n\n${unknown?'Known-price subtotal':'Estimated equipment total'}: ${formatKES(total)}\nName: ${customer.name}\nPhone: ${customer.phone}\nDelivery location: ${customer.location}\nNotes: ${customer.notes||'None'}\nPlease confirm stock, final prices and delivery charges.`;window.open(`https://wa.me/254717656407?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');};
  const active=category!=='All Products'||query||availability!=='all'||priceLimit!=='all'||sort!=='featured';
  return <main><section className="page-heading"><div className="site-container"><p className="eyebrow">THE SOLAR SHOP</p><h1>Good energy starts here.</h1><p>Find the right equipment. Compare prices. Send your order directly to our team.</p></div></section><section className="site-container py-10 pb-20"><div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Solar catalogue</h2><button onClick={()=>setCheckout(true)} disabled={!count} className="flex items-center gap-2 rounded-full bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><ShoppingBag size={17}/>Your order ({count})</button></div><div className="grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><Search size={18} className="absolute left-4 top-4 text-slate-400"/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search panels, batteries, inverters…" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-4"/></label><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)} className="h-12 rounded-xl border border-slate-200 px-4"><option value="featured">Featured order</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name: A–Z</option></select></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-bold">Category<select value={category} onChange={e=>setCat(e.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal"><option>All Products</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm font-bold">Availability<select value={availability} onChange={e=>setAvailability(e.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal"><option value="all">All availability</option><option value="in-stock">In stock</option><option value="out-stock">Out of stock</option><option value="unknown">Check availability</option></select></label><label className="text-sm font-bold">Price range<select value={priceLimit} onChange={e=>setPriceLimit(e.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 font-normal"><option value="all">All prices</option><option value="under-10000">Below KSh 10,000</option><option value="10k-50k">KSh 10,000–50,000</option><option value="over-50k">Above KSh 50,000</option></select></label></div><div className="mt-5 flex flex-wrap justify-between gap-3 text-sm"><p aria-live="polite" className="text-slate-500">{filtered.length} of {products.length} products{category!=='All Products'?` · ${category}`:''}</p>{active&&<button onClick={reset} className="font-bold text-emerald-700">Clear filters & sorting</button>}</div></div>
    <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(p=><article key={p.id} className="group flex flex-col overflow-hidden rounded-xl border border-slate-200 bg-white transition duration-300 hover:-translate-y-1 hover:shadow-lg"><button onClick={()=>setSelected(p)} aria-label={`View ${p.name}`} className="h-52 bg-white p-6"><img src={p.image} alt={p.name} loading="lazy" className="h-full w-full object-contain transition duration-500 group-hover:scale-105"/></button><div className="flex flex-1 flex-col border-t border-slate-100 p-5"><p className="text-xs font-semibold text-emerald-700">{p.category}</p><h3 className="mt-2 min-h-12 font-bold leading-6">{p.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{p.description}</p><div className="mb-5 mt-auto pt-5"><p className="text-xl font-extrabold">{getProductPrice(p)}</p><p className={`mt-1 text-xs ${p.stock&&p.stock>0?'text-emerald-700':'text-slate-500'}`}>{p.stock===undefined?'Check availability':p.stock>0?`${p.stock} in stock`:'Out of stock · enquire'}</p></div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setSelected(p)} className="rounded-lg border border-slate-200 py-3 text-sm font-bold hover:bg-emerald-50">Details</button><button onClick={()=>add(p)} className="rounded-lg bg-emerald-800 py-3 text-sm font-bold text-white hover:bg-emerald-700">Order</button></div></div></article>)}</div>{!filtered.length&&<div className="py-20 text-center"><PackageSearch size={42} className="mx-auto text-slate-300"/><h3 className="mt-4 text-xl font-bold">No matching products</h3><p className="mt-2 text-slate-500">Try another search or clear your filters.</p><button onClick={reset} className="text-link mt-5">Show all products</button></div>}</section>
    {selected&&<Dialog label={selected.name} onClose={()=>setSelected(null)}><div className="flex items-center justify-between border-b p-5"><h2 className="font-bold">Product details</h2><button aria-label="Close details" onClick={()=>setSelected(null)}><X/></button></div><div className="grid gap-7 p-6 md:grid-cols-2"><img src={selected.image} alt={selected.name} className="h-72 w-full object-contain"/><div><p className="text-sm text-emerald-700">{selected.category}</p><h3 className="mt-2 text-2xl font-bold">{selected.name}</h3><p className="mt-4 leading-7 text-slate-600">{selected.description}</p><p className="mt-5 text-2xl font-bold">{getProductPrice(selected)}</p><ul className="mt-5 space-y-2">{selected.features.map(f=><li key={f} className="flex gap-2 text-sm text-slate-600"><Check size={17} className="shrink-0 text-emerald-600"/>{f}</li>)}</ul><button onClick={()=>add(selected)} className="mt-6 w-full rounded-xl bg-emerald-800 py-3 font-bold text-white">Add to order</button></div></div></Dialog>}
    {checkout&&<Dialog label="Your WhatsApp order" onClose={()=>setCheckout(false)}><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-bold">Your order</h2><button aria-label="Close order" onClick={()=>setCheckout(false)}><X/></button></div><div className="grid gap-7 p-6 md:grid-cols-2"><div><div className="space-y-3">{cart.map(i=><div key={i.product.id} className="rounded-xl bg-slate-50 p-4"><h3 className="text-sm font-bold">{i.product.name}</h3><p className="mt-1 text-sm text-slate-500">{getProductPrice(i.product)}</p><div className="mt-3 flex items-center gap-3"><button aria-label={`Remove one ${i.product.name}`} onClick={()=>change(i.product.id,-1)} className="rounded-md border bg-white p-2"><Minus size={14}/></button><span>{i.quantity}</span><button aria-label={`Add one ${i.product.name}`} onClick={()=>change(i.product.id,1)} className="rounded-md border bg-white p-2"><Plus size={14}/></button></div></div>)}</div>{!cart.length&&<p>Your order is empty. Add a product to get started.</p>}<div className="mt-5 border-t pt-4"><p className="text-sm text-slate-500">{unknown?'Known-price subtotal':'Estimated equipment total'}</p><p className="text-2xl font-bold">{formatKES(total)}</p>{unknown&&<p className="mt-2 text-sm text-amber-700">Some items require a quote.</p>}</div><button onClick={()=>setCheckout(false)} className="text-link mt-5">Continue browsing</button></div><form onSubmit={submit} className="space-y-4">{[['name','Full name'],['phone','Phone / WhatsApp'],['location','Delivery town, address or landmark']].map(([key,label])=><label key={key} className="block text-sm font-bold">{label}<input required maxLength={200} type={key==='phone'?'tel':'text'} value={customer[key as keyof typeof customer]} onChange={e=>setCustomer({...customer,[key]:e.target.value})} className="mt-1.5 w-full rounded-xl border p-3"/></label>)}<label className="block text-sm font-bold">Notes (optional)<textarea rows={3} value={customer.notes} maxLength={1000} onChange={e=>setCustomer({...customer,notes:e.target.value})} className="mt-1.5 w-full rounded-xl border p-3"/></label><button disabled={!cart.length} className="w-full rounded-xl bg-emerald-800 p-4 font-bold text-white disabled:opacity-40">Send order on WhatsApp</button><p className="text-xs leading-5 text-slate-500">Our team confirms stock, prices and delivery before payment.</p></form></div></Dialog>}
  </main>;
}
