import { useEffect, useRef, useState } from 'react';
import { ImagePlus, Loader2, Save, Trash2, X } from 'lucide-react';
import { galleryCategories, type GalleryImage } from '../data/gallery';
import { deleteGalleryImage, listGallery, saveGalleryImage, updateGalleryImage } from '../data/galleryStore';
import Dialog from './Dialog';
async function compress(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG or WebP image.');if(file.size>15*1024*1024)throw new Error('Choose an image smaller than 15 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Could not prepare image.')),'image/webp',.84));return new File([blob],'gallery.webp',{type:'image/webp'});}
export default function GalleryAdmin(){
  const [images,setImages]=useState<GalleryImage[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [editing,setEditing]=useState<GalleryImage|null>(null);const [form,setForm]=useState({title:'',category:galleryCategories[0],location:'',published:true});const input=useRef<HTMLInputElement>(null);
  const load=async()=>{try{setImages(await listGallery(true));}catch(e){setError((e as Error).message);}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const save=async(e:React.FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);setError('');setNotice('');try{await saveGalleryImage(await compress(file),form);setFile(null);if(input.current)input.current.value='';setForm({...form,title:'',location:''});await load();setNotice(form.published?'Photo published to the gallery.':'Photo saved as a draft.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const update=async(item:GalleryImage)=>{setBusy(true);setError('');try{await updateGalleryImage(item);setEditing(null);await load();setNotice('Gallery updated.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const remove=async(item:GalleryImage)=>{if(!confirm(`Remove “${item.title}” from the gallery?`))return;setBusy(true);setError('');try{await deleteGalleryImage(item);await load();setNotice('Photo removed from the public gallery.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="mt-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Gallery</h2><p className="mt-1 text-slate-500">Upload a photo, add a caption, then publish.</p></div><a href="/gallery" target="_blank" rel="noreferrer" className="text-link">View public gallery</a></div>{error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
    <form onSubmit={save} className="mb-8 grid gap-6 rounded-2xl border border-slate-200 bg-white p-6 md:grid-cols-[1fr_1.4fr]"><div><label className="grid min-h-56 cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed border-emerald-200 bg-emerald-50/40 p-5 text-center">{preview?<img src={preview} alt="New photo preview" className="max-h-52 object-contain"/>:<span><ImagePlus className="mx-auto mb-3 h-9 w-9 text-emerald-600"/><strong>Choose a photo</strong><span className="mt-2 block text-sm text-slate-500">JPG, PNG or WebP · up to 15 MB<br/>Automatically resized for the website</span></span>}<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="mt-4 block w-full text-sm" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label></div><div className="grid gap-4"><label className="text-sm font-bold">Caption<input maxLength={150} required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-1 w-full rounded-xl border p-3" placeholder="e.g. Rooftop installation in Kisumu"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{galleryCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm font-bold">Location<input maxLength={150} value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="mt-1 w-full rounded-xl border p-3" placeholder="Town or project name"/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Publish immediately</label><button disabled={busy||!file} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-800 p-3 font-bold text-white disabled:opacity-50">{busy?<Loader2 size={18} className="animate-spin"/>:<ImagePlus size={18}/>} {form.published?'Upload & publish':'Save draft'}</button></div></form>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.map(item=><article key={item.id} className="overflow-hidden rounded-xl border bg-white"><img src={item.src} alt={item.title} className="h-48 w-full object-cover" loading="lazy"/><div className="p-4"><span className={`text-xs font-bold ${item.published?'text-emerald-700':'text-amber-700'}`}>{item.published?'Published':'Draft / hidden'}</span><h3 className="mt-2 font-bold">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.location||item.category}</p><div className="mt-4 flex flex-wrap items-center gap-2"><button disabled={busy} onClick={()=>setEditing({...item})} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-bold">Edit</button><button disabled={busy} onClick={()=>void update({...item,published:!item.published})} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-bold">{item.published?'Hide':'Publish'}</button><button disabled={busy} aria-label={`Delete ${item.title}`} onClick={()=>void remove(item)} className="ml-auto rounded-lg p-2 text-red-600"><Trash2 size={18}/></button></div></div></article>)}</div>
    {editing&&<Dialog label="Edit gallery photo" onClose={()=>setEditing(null)} className="max-w-lg"><form onSubmit={e=>{e.preventDefault();void update(editing);}} className="space-y-4 p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Edit photo</h2><button type="button" aria-label="Close editor" onClick={()=>setEditing(null)}><X/></button></div><label className="block text-sm font-bold">Caption<input required maxLength={150} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">Category<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{galleryCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm font-bold">Location<input value={editing.location} onChange={e=>setEditing({...editing,location:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="block text-sm font-bold">Display order<input type="number" min={0} value={editing.order} onChange={e=>setEditing({...editing,order:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3"/></label><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-800 p-3 font-bold text-white"><Save size={18}/>Save changes</button></form></Dialog>}
  </div>;
}
